In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

In [3]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [4]:
# Normalize the data using StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [5]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)



In [6]:
# Create a KNN classifier
knn = KNeighborsClassifier()



In [8]:
# Define the hyperparameter grid for grid search
param_grid = {
    'n_neighbors': np.arange(1, 10),  # Trying K values from 1 to 9
    'weights': ['uniform', 'distance'],
             }

In [9]:
# Perform grid search with cross-validation
grid_search = GridSearchCV(knn, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best K value and other optimal hyperparameters
best_k = grid_search.best_params_['n_neighbors']
best_weights = grid_search.best_params_['weights']

print(f"Best K value: {best_k}")
print(f"Best weight function: {best_weights}")


Best K value: 4
Best weight function: distance


In [10]:
# Train the final model using the best hyperparameters
best_knn = KNeighborsClassifier(n_neighbors=best_k, weights=best_weights)
best_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4, weights='distance')

In [11]:
# Make predictions on the test set
y_pred = best_knn.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[ 8  0  0]
 [ 0  8  0]
 [ 0  1 13]]


In [14]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test accuracy: {accuracy:.2f}")

Test accuracy: 0.97
